# Generated by Django 3.2.3 on 2021-06-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('author_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, unique=True)),
                ('isbn', models.BigIntegerField()),
                ('book_desc', models.TextField()),
                ('phone_number', models.BigIntegerField()),
                ('pagenum', models.IntegerField()),
                ('image', models.ImageField(default='no', upload_to='book/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=200)),
                ('cat_slug', models.SlugField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=200, unique=True)),
                ('prod_slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_desc', models.TextField()),
                ('prod_image', models.ImageField(default='emp', upload_to='product/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isavaliabe', models.BooleanField(default=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
