# Generated by Django 3.2.3 on 2021-06-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lable', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=220)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('item_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
