# Generated by Django 3.2.3 on 2021-06-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Items', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
